[tool.poetry]
name = "spinespy"
version = "1.2.1"
description = "AI-powered posture & focus monitor for macOS menubar"
authors = ["jananadiw"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
opencv-python = "^4.8.0"
mediapipe = "^0.10.0"
rumps = "^0.4.0"
pyobjc-framework-Cocoa = "^12.1"

[tool.poetry.scripts]
start = "spinespy.cli:start"
test-phone = "spinespy.cli:test_phone"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pyinstaller (>=6.18.0,<7.0.0)",
    "pytest (>=9.0.3,<10.0.0)"
]
